/**
 * Migration 023: marketplace_skills — add 'withdrawn' to review_status CHECK
 *
 * The withdraw endpoint (DELETE /skills/:slug) performs a soft-delete by
 * setting review_status = 'withdrawn'. The original CHECK constraint from
 * migration 001 only allowed pending, approved, rejected, deprecated.
 *
 * This migration drops and recreates the constraint to include 'withdrawn'.
 */
import type { QueryResultRow } from "pg";

type QueryFn = <T extends QueryResultRow = QueryResultRow>(
  text: string,
  params?: unknown[],
) => Promise<import("pg").QueryResult<T>>;

export async function up(query: QueryFn): Promise<void> {
  // Drop old constraint (name auto-generated by PG as marketplace_skills_review_status_check)
  await query(`
    ALTER TABLE marketplace_skills
      DROP CONSTRAINT IF EXISTS marketplace_skills_review_status_check;
  `);
  await query(`
    ALTER TABLE marketplace_skills
      ADD CONSTRAINT marketplace_skills_review_status_check
        CHECK (review_status IN ('pending', 'approved', 'rejected', 'deprecated', 'withdrawn'));
  `);
}

export async function down(query: QueryFn): Promise<void> {
  await query(`
    ALTER TABLE marketplace_skills
      DROP CONSTRAINT IF EXISTS marketplace_skills_review_status_check;
  `);
  await query(`
    ALTER TABLE marketplace_skills
      ADD CONSTRAINT marketplace_skills_review_status_check
        CHECK (review_status IN ('pending', 'approved', 'rejected', 'deprecated'));
  `);
}
