// =============================================================================
// src/setup/wizard.ts
// =============================================================================

import { existsSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve } from "node:path";
import { detectEnvironment, type EnvironmentReport } from "./environment.js";

export type WizardMode = "personal" | "enterprise_worker";
export type AuthChoice = "none" | "local";
export type ModelStrategy = "all_cloud" | "all_local" | "hybrid" | "manual";
export type ModelSource = "auto" | "hf" | "hf_mirror" | "enterprise" | "manual";

export interface WizardInput {
  environment: EnvironmentReport;
  mode: WizardMode;
  authChoice?: AuthChoice;          // personal only
  adminUsername?: string;
  adminPassword?: string;
  hubUrl?: string;                  // enterprise_worker
  joinToken?: string;
  modelStrategy: ModelStrategy;
  modelSource: ModelSource;
  enterpriseModelsUrl?: string;
  providerKeys: Record<string, string>;  // cloud 模式各 provider key
}

export interface WizardResult {
  configYaml: string;
  envVars: Record<string, string>;
}

export function isSetupComplete(): boolean {
  return existsSync(getFlagPath());
}

function getFlagPath(): string {
  return process.env.DA_SETUP_FLAG || resolve(process.cwd(), "data/setup-complete.flag");
}

function getConfigPath(): string {
  return process.env.DA_CONFIG_PATH || resolve(process.cwd(), "data/config.yaml");
}

export async function markSetupComplete(): Promise<void> {
  mkdirSync(resolve(getFlagPath(), ".."), { recursive: true });
  writeFileSync(getFlagPath(), new Date().toISOString());
}

export function runWizard(input: WizardInput): WizardResult {
  const configYaml = generateConfigYaml(input);
  const envVars = generateEnvVars(input);
  return { configYaml, envVars };
}

function generateConfigYaml(input: WizardInput): string {
  const lines: string[] = [
    "# DeepAnalyze configuration (generated by setup wizard)",
    `generated_at: ${new Date().toISOString()}`,
    "",
    "models:",
    `  source: ${input.modelSource}`,
  ];
  if (input.enterpriseModelsUrl) {
    lines.push(`  enterprise_url: ${input.enterpriseModelsUrl}`);
  }
  if (input.modelStrategy === "all_cloud" || input.modelStrategy === "hybrid") {
    lines.push("", "providers:");
    for (const [k, v] of Object.entries(input.providerKeys)) {
      lines.push(`  ${k}: ${v}`);
    }
  }
  return lines.join("\n") + "\n";
}

function generateEnvVars(input: WizardInput): Record<string, string> {
  const env: Record<string, string> = {};
  if (input.mode === "enterprise_worker") {
    env.DA_AUTH_MODE = "hub";
    env.DA_HUB_URL = input.hubUrl!;
    env.DA_JOIN_TOKEN = input.joinToken!;
  } else if (input.authChoice === "local") {
    env.DA_AUTH_MODE = "local";
  } else {
    env.DA_AUTH_MODE = "none";
  }
  return env;
}

export async function saveConfig(result: WizardResult): Promise<void> {
  mkdirSync(resolve(getConfigPath(), ".."), { recursive: true });
  writeFileSync(getConfigPath(), result.configYaml);
  // 写 .env 变量追加（如果不存在）
  const envPath = resolve(process.cwd(), ".env");
  if (existsSync(envPath)) {
    const { readFileSync, appendFileSync } = await import("node:fs");
    const existing = readFileSync(envPath, "utf-8");
    const newLines = Object.entries(result.envVars)
      .filter(([k]) => !existing.includes(`${k}=`))
      .map(([k, v]) => `${k}=${v}`)
      .join("\n");
    if (newLines) appendFileSync(envPath, "\n# Setup wizard generated\n" + newLines + "\n");
  }
  await markSetupComplete();
}
